Repository ExoCTK/exoctk, pull requests merged in 2019-03, with the labels that each got.

#224 ExoMAST patch for setup.py
  setup.py
Labels: High Priority, Installation

#235 Make sphinx autodoc work again
  docs/index.rst
  docs/source/exoctk.contam_visibility.rst
  docs/source/exoctk.groups_integrations.rst
  docs/source/exoctk.integrations_groups.rst
  docs/source/exoctk.limb_darkening.rst
  docs/source/exoctk.phase_constraint_overlap.rst
  docs/source/exoctk.rst
  docs/source/exoctk.tests.rst
  docs/source/modules.rst
  env/environment-3.5.yml
  env/environment-3.6.yml
  env/environment-3.7.yml
  exoctk/phase_constraint_overlap/__init__.py
  setup.py
Labels: Documentation

#219 LDC Form validation
  exoctk/exoctk_app/__init__.py
  exoctk/exoctk_app/app_exoctk.py
  exoctk/exoctk_app/form_validation.py
  exoctk/exoctk_app/templates/limb_darkening.html
  exoctk/exoctk_app/templates/limb_darkening_results.html
  exoctk/limb_darkening/limb_darkening_fit.py
  exoctk/utils.py
Labels: Enhancement, High Priority, Web App
