Repository ExoCTK/exoctk, pull requests merged in 2021-09, with the labels that each got.

#513 Add moar unit tests
  env/environment-3.7.yml
  env/environment-3.8.yml
  env/environment-3.9.yml
  exoctk/contam_visibility/miniTools.py
  exoctk/contam_visibility/resolve.py
  exoctk/tests/__init__.py
  exoctk/tests/test_contam_visibility.py
  exoctk/tests/test_groups_integrations.py
  exoctk/tests/test_log_exoctk.py
  exoctk/tests/test_phase_constraint_overlap.py
  exoctk/tests/test_throughputs.py
  exoctk/tests/test_visibilityPA.py
  pip_requirements.txt
  setup.py
Labels: Category: Software Standards

#517 Update readthedocs
  env/environment-3.7.yml
  env/environment-3.8.yml
  env/environment-3.9.yml
  pip_requirements.txt
  setup.py
Labels: Urgent: Bug, Urgent: Question, Category: Documentation, Tool: all, dependencies

#519 Fix ExoCTK crashing at import due to field_simulator.py trace check
  exoctk/contam_visibility/field_simulator.py
Labels: Urgent: Bug, Tool: contam_visibility
